// <auto-generated />
using System;
using Arpg.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arpg.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arpg.Core.Models.Customer.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Arpg.Core.Models.Customer.Code", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("AccountId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("Arpg.Core.Models.Customer.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Arpg.Core.Models.Sheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("Arpg.Core.Models.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Arpg.Core.Models.Customer.Account", b =>
                {
                    b.HasOne("Arpg.Core.Models.Customer.User", null)
                        .WithOne()
                        .HasForeignKey("Arpg.Core.Models.Customer.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arpg.Core.Models.Customer.Code", b =>
                {
                    b.HasOne("Arpg.Core.Models.Customer.Account", null)
                        .WithMany("Codes")
                        .HasForeignKey("AccountId");

                    b.HasOne("Arpg.Core.Models.Customer.Account", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arpg.Core.Models.Sheet", b =>
                {
                    b.HasOne("Arpg.Core.Models.Customer.User", null)
                        .WithMany("Sheets")
                        .HasForeignKey("UserId");

                    b.OwnsOne("System.Collections.Generic.Dictionary<System.Guid, object>", "Data", b1 =>
                        {
                            b1.Property<Guid>("SheetId");

                            b1.HasKey("SheetId");

                            b1.ToTable("Sheets");

                            b1
                                .ToJson("Data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SheetId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Arpg.Core.Models.Template", b =>
                {
                    b.OwnsOne("Arpg.Core.Models.TemplateStructure", "Structure", b1 =>
                        {
                            b1.Property<Guid>("TemplateId");

                            b1.HasKey("TemplateId");

                            b1.ToTable("Templates");

                            b1
                                .ToJson("Structure")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");

                            b1.OwnsMany("Arpg.Core.Models.TemplateCategory", "Categories", b2 =>
                                {
                                    b2.Property<Guid>("TemplateStructureTemplateId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<Guid>("Id");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<int>("Order");

                                    b2.HasKey("TemplateStructureTemplateId", "__synthesizedOrdinal");

                                    b2.ToTable("Templates");

                                    b2.WithOwner()
                                        .HasForeignKey("TemplateStructureTemplateId");
                                });

                            b1.OwnsMany("Arpg.Core.Models.TemplateField", "Fields", b2 =>
                                {
                                    b2.Property<Guid>("TemplateStructureTemplateId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<Guid>("CategoryId");

                                    b2.Property<string>("DefaultValue");

                                    b2.Property<Guid>("Id");

                                    b2.Property<bool>("IsRequired");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<int>("Type");

                                    b2.HasKey("TemplateStructureTemplateId", "__synthesizedOrdinal");

                                    b2.ToTable("Templates");

                                    b2.WithOwner()
                                        .HasForeignKey("TemplateStructureTemplateId");
                                });

                            b1.Navigation("Categories");

                            b1.Navigation("Fields");
                        });

                    b.Navigation("Structure")
                        .IsRequired();
                });

            modelBuilder.Entity("Arpg.Core.Models.Customer.Account", b =>
                {
                    b.Navigation("Codes");
                });

            modelBuilder.Entity("Arpg.Core.Models.Customer.User", b =>
                {
                    b.Navigation("Sheets");
                });
#pragma warning restore 612, 618
        }
    }
}
